version: '3'
services:

  flask:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 3031:3031
    restart: always
    env_file:
      ./.env
    tty: yes
    volumes:
      - ./requirements.txt:/usr/src/flask_app
      - ./app.py:/usr/src/app/app.py

  web:
    container_name: web-server
    hostname: web-server
    build: ./web
    volumes: 
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./tmp/nginx_log:/var/log/nginx
    ports:
      - 4231:80

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   ports:
  #     - "4040:4040"
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml